"""Add RefreshTokens table

Revision ID: 3767d05b9716
Revises: dfb1707e8f22
Create Date: 2026-07-13 01:20:12.506971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3767d05b9716'
down_revision: Union[str, Sequence[str], None] = 'dfb1707e8f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='refresh_tokens_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='refresh_tokens_pkey')
    )
    op.create_index('refresh_tokens_token_key', 'refresh_tokens', ['token'], unique=True)
    op.create_foreign_key(None, 'threat_reports', 'groq_call_logs', ['groqCallLogId'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threat_reports', type_='foreignkey')
    op.drop_index('refresh_tokens_token_key', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
