"""Add indexes and investigation fields

Revision ID: ae9076540038
Revises: 
Create Date: 2026-07-13 00:37:33.533094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae9076540038'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('network_edges_createdAt_idx', 'network_edges', ['createdAt'], unique=False)
    op.create_index('network_nodes_createdAt_idx', 'network_nodes', ['createdAt'], unique=False)
    op.add_column('threat_reports', sa.Column('officerNotes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True))
    op.add_column('threat_reports', sa.Column('evidenceHistory', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True))
    op.add_column('threat_reports', sa.Column('auditTrail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threat_reports', 'auditTrail')
    op.drop_column('threat_reports', 'evidenceHistory')
    op.drop_column('threat_reports', 'officerNotes')
    op.drop_index('network_nodes_createdAt_idx', table_name='network_nodes')
    op.drop_index('network_edges_createdAt_idx', table_name='network_edges')
    # ### end Alembic commands ###
