"""Add GroqCallLogs metrics

Revision ID: dfb1707e8f22
Revises: ae9076540038
Create Date: 2026-07-13 00:45:18.432177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb1707e8f22'
down_revision: Union[str, Sequence[str], None] = 'ae9076540038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groq_call_logs', sa.Column('estimatedCost', sa.Double(precision=53), server_default=sa.text('0.0'), nullable=False))
    op.add_column('groq_call_logs', sa.Column('retryCount', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groq_call_logs', 'retryCount')
    op.drop_column('groq_call_logs', 'estimatedCost')
    # ### end Alembic commands ###
